---
# NodePort service to expose Coroot UI and API
# Exposes the CR-created coroot-coroot service (which has projects configured)
apiVersion: v1
kind: Service
metadata:
  name: coroot-nodeport
  namespace: coroot
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: coroot
    app.kubernetes.io/part-of: coroot
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32702  # Same NodePort as before for consistency
    - name: otel
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30275  # Same as before
