apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mcp-infisical-credentials
  namespace: mcp-servers
  labels:
    app: infisical-mcp
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /infrastructure/infisical
  managedSecretReference:
    secretName: mcp-infisical-credentials
    secretNamespace: mcp-servers
    secretType: Opaque
    creationPolicy: Owner
