apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  namespace: reflector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reflector
subjects:
  - kind: ServiceAccount
    name: reflector
    namespace: reflector
