apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backrest-monit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://github.com/charlieshreck/monit_homelab.git
    targetRevision: main
    path: kubernetes/applications/backrest
  destination:
    server: https://10.10.0.30:6443
    namespace: backrest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
