---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: monitoring
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.28
    path: deploy/chart/local-path-provisioner
    helm:
      valuesObject:
        storageClass:
          name: local-path
          defaultClass: true
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/lib/rancher/local-path-provisioner
  destination:
    server: https://10.30.0.20:6443
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
