---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector-monit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: monitoring
  source:
    repoURL: https://github.com/charlieshreck/monit_homelab.git
    targetRevision: main
    path: kubernetes/platform/reflector
  destination:
    server: https://10.10.0.30:6443
    namespace: reflector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
