---
# Grafana NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30081
---
# Prometheus NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30082
---
# Alertmanager NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: kube-prometheus-stack-alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      nodePort: 30083
---
# VictoriaMetrics NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: victoria-metrics-single-server
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      nodePort: 30084
---
# VictoriaLogs NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: victorialogs-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: victoria-logs-single-server
  ports:
    - name: http
      port: 9428
      targetPort: 9428
      nodePort: 30085
---
# Gatus NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: gatus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gatus
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30086
---
# Beszel NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: beszel-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: beszel
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30087
    - name: agent
      port: 45876
      targetPort: 45876
      nodePort: 30088
