# SealedSecret for Infisical Operator Bootstrap Credentials
# Encrypted with cluster-specific sealing key - safe to commit to git
# Only decryptable by the sealed-secrets controller in the monit cluster
#
# Re-sealed 2026-02-19 after Talos dual-NIC rebuild (previous key no longer valid)
# For fresh deployments, see: /home/agentic_lab/runbooks/infrastructure/sealed-secrets.md
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: universal-auth-credentials
  namespace: infisical-operator-system
spec:
  encryptedData:
    clientId: AgDIjeJ1DPXSlLPW3dUJ/ds+v65N4pPttG3XNYtJrcxg6lbqePmk28NBen3yCb0P/Kr39YS8ezPk1in1yznAhaZ2dJx+X7Pb8dfnCN/jKh/RLumyyUqzssGDpC8sPCXrIBybiQQQN+gXJLLDiFn+GFV3oqulmk0QymsaN+1h9x7myBTQ7Z0PMChsFznt/+nUl1WsrY3GdC8NgVNApOM79zMLK8fpRfokTWwCKYLAAnWzTECIP8XqrlaMRjtdziaMYtZ+tIp7TcmC0Y9UXVFEoftFwL1TqnIuSf/y6f9AykrIoVsv9gHrks/aXtfWZ6HWbmFkLdy1KIh+7K/STR6k9zaO0/RlWul1SH7/r4Y083rtU7+/9Rowr9FR5pxM8/Q48Jw6ydMrguTy0Uj5RegoQYrNsaSlfjDm0/hG7YcX9cQT1QW07E0mMNYHG4FxWB2N9Rmsqx6C36Qhw9CQqqbZuksArgs8fhoMYYawvVv4lwZfdqWxrNdJrhHfmuJpjdFfbjBXXnoZoowCJUOZCEfTfK4UFn5pNvYjD7hcZt9DDq9AtGgxAxDUySJmoweAjjeUGtqU4TfA5eUvNk/pdLKvzvlRd8eCwjCrewcU9029HahOzfxUhuqGUbpouiTiXP4Ohh/1MDF/FcvwpB/v5buzyHsvB70EboSUx+7oEVdJBc6DCFth1bhDSWSzzRr+KM+6ZCAX+T4ljXQLWqJ1lrd2kNoprUj2BfLI3XnNfdrYQje/JEq8VwI=
    clientSecret: AgBSsLg+OEs7wK5R4cZ8PeFJwjRwK+IRRV4rGZomhpIUIC71rMfnLApKRHrcuKq0T7EAvuADKsL3XJ1ENkZ4MqphDv5NdwZr0MNj2Y6Q49H4hfibQeDzMdakWdfNmwm1O38H47RlZJ70o7q7CxNz6nJbOgCPJ+ZBzi34O7OaHoQYgh529gQokjqYsSCXWIRCQ8erEgytcb+QWTrz/9YzM5P8u0P0EwsHHMU6HuFHxzItMSWer2XVCuHtrBzn+kss6aKnLr+ZyjT6hLbXz0JMYRSBjKtOF638cMEVYBGkmIAj1hrffzXLXnbsy0vCVG9WM4M3DTWzd8VmkiQJkwSdnuvqHCZSzFSvo7jnMk+moCYTp1jezJhpwa8ij+7clf9hJ/Uq40Ww/8oqtoJ01h7bltQ3J6dSnIgDEIwfekbdhtDxtrkaV2IBvfXuihTKSjgJkVDjslRytdOndKvc1q6yvYajUzPg9rbPc2nx6eMKST1EA/r1KKePnpcD4uZiMLZgBEfpybedfO+MY8kDmrkT3/nYGoyoUD3OmDfw4Q31hvcVS7F16Owc2AltMuMvD04eCtn0EgsYI0SIO1n3mffXY2UeKq6x+e/WubBOdUaJ+IeUSVl7GxLqi0wsf2Y4C2T9aNJJnJLRERbZ9g1+i1sWxZLX1G5NzucLCPhUmGHXMk3a9o73QfQpLdLqYaAKyee2hV54Rc1mQpBwnaEB7AlxhW6kj3OM1MkYlmo39umudmSTj0WxIjCZoJKgXIim6CNsgRx1gM8LW21Y8vqKmGQ4/p3j
  template:
    metadata:
      name: universal-auth-credentials
      namespace: infisical-operator-system
    type: Opaque
