# SealedSecret for Infisical Operator Bootstrap Credentials
# Encrypted with cluster-specific sealing key - safe to commit to git
# Only decryptable by the sealed-secrets controller in the monit cluster
#
# For fresh deployments, see: /home/agentic_lab/runbooks/infrastructure/sealed-secrets.md
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: universal-auth-credentials
  namespace: infisical-operator-system
spec:
  encryptedData:
    clientId: AgCKKbn1zoQA965gDKJRouffwlQrjsKURKRclQAzN6mE1m4xdB1EYxmlg5SyLy1KUdBZOtjMBD7A+HTAF8hrqg+a6XeEhc2rVl/k4wgbZYZDbuIyPzAkABYhTeufVY6t2YGYUfs2uopqdqCy77rMvDG83YK8W43R8v4ECOUavPTg84S+ANJVa3SC9jIjOPRF+FE87h76GQX4OJfpcpYgulr+63+L5MnzCzBUQHfnvHmKNuGVGdKpzOlLm0HSMF2pZ4bZurkCu0i/uaQN3vqUuFB4siiiNqnb1XOagzctkY2IdFRMkuQGvL6hGwZcYkgf8uFP5HPyPE5uqSjuYF/9UqPwzkf2Ity3KqK4+9qCN3P2HIh3iESrchVEPplDPEscG48ne8DElceJ3EAEjRhMzG05csShyk+Bp7V+LaghozoT0W8rdCVPzouOvnePVMXJoFCWqjQo/jsgJ2FM/QS5YDFs7e5boFOtpQoVYjDz6QMYjKJ8/XuYuNijm85DOcBXf688eoYIzP3k5zPUCZ+HAZIguGTIIiR0+MAmnaGqWigl68vbkl0Re86IhMBO+750WYMMNyshOfNNGh3Fg7K3P0fYXj9eB7sOgZ8UEytVmogzxA2aACVHtUwqA9NdrjTv752P+J9mnC5683fD42KUs9QqREjm5HwxKeeHIwbJ2Zk+cPn2JQZmFpF8twy9fBh0CT7GnP1KKCwhnigzS96U0tqO3W/D6A3ZnpTPvxMqiGXlxbLde+Y=
    clientSecret: AgAEEnem6n/2p742m4lC1+xTMYj9R/WgsxoCA9FIQZvWOdi+YSv1YtDKXi2ppmQkJ08pn2OLhv+uyLVeYsNANuZS6S9FsOBU9SxoL35f0rGfDE6fckcctMnqxD6R6R/nqybltzNgmxwtFYESkXDnyPUc2+FuqAP6fP0u7wYHdtLZib1BaeGCmc+5nHhOwf7Gbz7EXVjwbhFYQdt/ujVyxpvSPh1foEhmAmdLPLJtMjyarLMPpV0B+HViyCjd57eyA3dtg6dzEanbC+NdFyAU4uZ1Ljp1T4cxFhJd0Bh51DLxNiUgCl34o9Ln3o7dThosH/Tpp2aFhtw3js80ERoMRUJIPCz4q7YUA/9ye/3P74BggGY4BNw3kQX5k4VzFBpvnYt8iZXgIM1eOJBzazuMbOGu9C//F3Avnsb0A5y6jJp/bAEDtSMR0TK07JWbD4Afwrm6ysDgwzl0HJ0Jo6STpbqKWZEDQc/sbiOj0cRu30pag4L2SRiUQTs2gxuCcC/d+gxodJ4dFl3V2wb/BeWom9dDnNTGvUH4YikOYF18TGvMOIfOFgMG7z/dshZijP2QckUEX6mLeFJXbQYIAC3410KUlf6A0Zqtfe8HscMxiGYsCprIN4ErW1iWKuAWvz4blWs4/qsI6DaagamEYANY71WmUBPdvLKYh8lLhg2mBP7WuSK9/eelMBQJwlEBQw1y3F4BrmybKcjjt0XA6Y0lM5Uof5vG5TxQRfHGKa13ofFlkq9fgEd98WqIE5XrgsXFrFsGnx5+tMUitD/9jSZB5LUI
  template:
    metadata:
      name: universal-auth-credentials
      namespace: infisical-operator-system
    type: Opaque
