apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mcp-credentials
  namespace: mcp-servers
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /mcp-credentials
  managedSecretReference:
    secretName: mcp-credentials
    secretNamespace: mcp-servers
    secretType: Opaque
    creationPolicy: Owner
