---
apiVersion: v1
kind: Service
metadata:
  name: victoria-logs-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-logs-single
    app.kubernetes.io/instance: victoria-logs
    app.kubernetes.io/component: nodeport
spec:
  type: NodePort
  ports:
    - name: http
      port: 9428
      targetPort: 9428
      nodePort: 30085
      protocol: TCP
  selector:
    app: victoria-logs
    app.kubernetes.io/instance: victoria-logs
    app.kubernetes.io/name: victoria-logs-single
